### ISSUE TITLE
Broken internal link in the /30-days-of-super-productivity/ article

### ISSUE THREAD

**Issue by ckrybus** [sirupsen/sirupsen.com#7]
Hi,

on your https://sirupsen.com/30-days-of-super-productivity/ page you link to https://sirupsen.com/my-journey-to-the-international-olympiad-in-informatics/ but the page doesn't exist.

It seems that you accidentally renamed the 2012-06-26-my-journey-to-the-international-olympiad-in-informatics.md file to my-journey-to-the-international-olympiad-in-informatic.md (the s is missing) while migrating to hugo.

**Comment by sirupsen** [comment]
Thanks, should be fixed!
